routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('groups', 'GroupController');
Route::resource('students', 'StudentController');
Route::resource('marks', 'MarkController');
Route::resource('subjects', 'SubjectController');
Route::resource('photos', "PhotoController");


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = ['group_name', 'description'];

    public $timestamps = false;

    public function students()
    {
        return $this->hasMany(Student::class);
    }
}

app/Models/Student.php
<?php

namespace App\Models;

use http\Env\Request;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['name', 'birthday', 'group_id'];

    public $timestamps = false;

    public function groups()
    {
        return $this->belongsTo(Group::class);
    }

    public function marks()
    {
        return $this->hasMany(Mark::class);
    }

    public function photos()
    {
        return $this->hasOne(Photo::class);
    }
    
    public function scopeName($query, $name)
    {
        $name && $query->where('name', 'like', "%{$name}%");
    }

    public function scopeGroup($query)
    {
        return $query->where('group_id', request('group_id'));
    }

    public function scopeFilter($query)
    {
        if (request('name') && (request()->name)) {
            return $query = $query->Name(request('name'));
        }

        if (request('group_id') && (request()->group_id)) {
            return $query = $query->Group();
        }
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use App\Models\Subject;

use App\Http\Requests\StoreGroup;
use Illuminate\Http\Request;

class GroupController extends Controller
{

    public function index()
    {
        $subjects = Subject::all();
        $groups = Group::all();

        return view('groups.show.index', compact('groups', 'subjects'));
    }

    public function create()
    {
        return view('groups.create');
    }

    public function store(StoreGroup $request)
    {
        Group::create($request->all());

        return redirect('groups');
    }

    public function edit(Group $group)
    {
        return view('groups.edit', compact('group'));
    }

    public function update(StoreGroup $request, Group $group)
    {
        $group->update($request->all());

        return redirect('groups')->with('success', 'Group has been updated');
    }

    public function show(Group $group)
    {
        $subjects = Subject::all();

        return view('groups.show', compact('group', 'subjects'));
    }

    public function destroy(Group $group)
    {
          $group->delete();

          return redirect('groups')->with('success', 'Group has been deleted');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Subject;
use App\Models\Student;

use App\Http\Requests\StoreStudent;

class StudentController extends Controller
{
    public function index()
    {
        $subjects = Subject::all();
        $students = Student::with('marks')
                    ->Filter()
                    ->paginate(2)
                    ->appends([
                      'group_id' => request()->group_id,
                      'name' => request()->name
                    ]);

        return view('groups.students.show.index', compact('students', 'subjects'));
    }
    public function create()
    {
        return view('groups.students.create');
    }

    public function store(StoreStudent $request, Student $student)
    {
        $student->create($request->all());

        return back();
    }

    public function show(Student $student)
    {
        $subjects = Subject::all();

        return view('groups.students.show', compact('student', 'subjects'));
    }

    public function edit(Student $student)
    {
        return view('groups.students.edit', compact('student'));
    }

    public function update(StoreStudent $request, Student $student)
    {
        $student->update($request->all());

        return back();
    }

    public function destroy(Student $student)
    {
        $student->delete();

        return back();
    }
}

resources/views/groups/students/create.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div>
    <div>Add Student
    </div>
    <div class="card-body">
        <form  action="{{ route('students.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Student Name</label>
                <input type="text" class="form-control" name="name"/>
            </div>
            <div class="form-group">
                <label for="birthday">Student Birthday</label>
                <input type="date" class="form-control" name="birthday"/>
            </div>
            <div class="form-group">
                <label for="group_id">Group Number</label>
                <input type="text" class="form-control" name="group_id"/>
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
</div>

resources/views/groups/students/edit.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div>
    <div class="card-header">Edit Student
    </div>
    <br />
    <form method="post" action="{{route('students.update', $student->id)}}">
        @method('PATCH')
        @csrf
        <div class="form-group">
            <label for="name">Student Name</label>
            <input type="text" class="form-control" name="name" value={{ $student->name }} />
        </div>
        <div class="form-group">
            <label for="birthday">Student Birthday</label>
            <input type="date" class="form-control" name="birthday" value={{ $student->birthday }} />
        </div>
        <div class="form-group">
            <label for="group">Group ID</label>
            <input type="text" class="form-control" name="group_id" value={{ $student->group_id }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>

resources/views/groups/students/filter.blade.php
<div class="container">
  <a href="{{route('students.index')}}" class="btn btn-primary">Reset</a>
    <form action="{{route('students.index')}}" method="GET" class="form from-group">
      @csrf
        <div class="form-group">

          <div class="form-group">
            <ul class="list-group">
                @foreach($subjects as $subject)
                 <li class="list-group-item">
                    <input type="radio" @if ($subject->id == request()->subject_id) checked @endif name="subject_id" value="{{ $subject->id }}">{{ $subject->subject_name }}
                 </li>
                @endforeach
            </ul>
          </div>

          <div class="form-group">
            <select name="mark">
              <option @if (5 == request()->mark) selected @endif>5</option>
              <option @if (4.5 == request()->mark) selected @endif>4.5</option>
              <option @if (3 == request()->mark) selected @endif>3</option>
            </select>
          </div>
        </div>
      <div class="form-group">

          <div class=form-group>
            <label for="name">Input Student Name</label>
            <input type="text" name="name" value="{{ request()->name }}">
          </div>

          <div class='form-group'>
            <label for="group_id">Input Group Number</label>
            <input type="text" name="group_id"  value="{{ request()->group_id }}">
          </div>
        <button type="submit" class="btn">Filter</button>
      </div>
  </form>
</div>

resources/views/groups/students/show.blade.php
@extends ('layouts.app')

@section ('content')
    <div>
        <h1>{{$student->name}}</h1>

        @include('groups.students.edit.image_crud')
        @include('groups.students.edit')

        <table class="table">
            <thead class="thead-dark">
                <tr class="table-striped">
                    @foreach($subjects as $subject)
                        <td>
                            {{$subject->subject_name}}
                        </td>
                    @endforeach
                </tr>
            </thead>
            <tbody class="table table-striped">
                <tr>
                    @foreach($subjects as $subject)
                        <td>
                            <dl class="list-group ">
                                @foreach($student->marks as $mark)
                                    @if($subject->id == $mark->subject_id)
                                        <dd class="align-content-center">
                                            {{$mark->mark}}
                                            <form action="{{route('marks.destroy', $mark->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </dd>
                                    @endif
                                @endforeach
                            </dl>
                        </td>
                    @endforeach
                </tr>
            </tbody>
        </table>
    </div>
    @include('groups.students.edit.table_marks_store')
@endsection