routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('groups', 'GroupController');
Route::resource('students', 'StudentController');
Route::resource('marks', 'MarkController');
Route::resource('subjects', 'SubjectController');
Route::resource('photos', "PhotoController");


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use http\Env\Request;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['name', 'birthday', 'group_id'];

    public $timestamps = false;

    public function groups()
    {
        return $this->belongsTo(Group::class);
    }

    public function marks()
    {
        return $this->hasMany(Mark::class);
    }

    public function photos()
    {
        return $this->hasOne(Photo::class);
    }
    
    public function scopeName($query, $name)
    {
        $name && $query->where('name', 'like', "%{$name}%");
    }

    public function scopeGroup($query)
    {
        return $query->where('group_id', request('group_id'));
    }

    public function scopeFilter($query)
    {
        if (request('name') && (request()->name)) {
            return $query = $query->Name(request('name'));
        }

        if (request('group_id') && (request()->group_id)) {
            return $query = $query->Group();
        }
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Subject;
use App\Models\Student;

use App\Http\Requests\StoreStudent;

class StudentController extends Controller
{
    public function index()
    {
        $subjects = Subject::all();
        $students = Student::with('marks')
                    ->Filter()
                    ->paginate(2)
                    ->appends([
                      'group_id' => request()->group_id,
                      'name' => request()->name
                    ]);

        return view('groups.students.show.index', compact('students', 'subjects'));
    }
    public function create()
    {
        return view('groups.students.create');
    }

    public function store(StoreStudent $request, Student $student)
    {
        $student->create($request->all());

        return back();
    }

    public function show(Student $student)
    {
        $subjects = Subject::all();

        return view('groups.students.show', compact('student', 'subjects'));
    }

    public function edit(Student $student)
    {
        return view('groups.students.edit', compact('student'));
    }

    public function update(StoreStudent $request, Student $student)
    {
        $student->update($request->all());

        return back();
    }

    public function destroy(Student $student)
    {
        $student->delete();

        return back();
    }
}

resources/views/groups/students/edit/create_subject.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div>
    <h3>Add Subject</h3>
    <div class="card-body">
        <form action="{{ route('subjects.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="subject_name">Subject Name</label>
                <input type="text" class="form-control" name="subject_name" />
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
</div>

resources/views/groups/students/edit/image_crud.blade.php
@if ($student->photos === null )
<div class="container">
    <div>
        <img src="/public/storage/avatar.png" class="img-thumbnail">
    </div>
    <form enctype="multipart/form-data" action="{{ route('photos.store') }}" method="POST">
        <div class="form-group">
          @csrf
          <input type="hidden" name="student_id" value="{{ $student->id }}">
          <input type="file" name="file" id="file" required>
          <button type="submit">Загрузить</button>
        </div>
    </form>
</div>
@else
<div class="container">
  <img src="/public/storage/{{ $student->photos->photo }}" class="img-thumbnail">
    <form enctype="multipart/form-data" action="{{ route('photos.update', $student->photos->id) }}" method="POST">
        <div class="form-group">
          @csrf
          @method('PUT')
          <input type="hidden" name="student_id" value="{{ $student->id }}">
          <input type="file" name="file" id="file" required>
          <button type="submit">Обновить</button>
        </div>
    </form>
</div>
@endif

resources/views/groups/students/edit/index_subject.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-body">
        <h2>Subjects List</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>Subject ID</td>
                    <td>Subject Name</td>
                </tr>
            </thead>
            <tbody>
            @foreach($subjects as $subject)
                <tr>
                    <td>{{$subject->id}}</td>
                    <td>{{$subject->subject_name}}</td>
                    <td>
                        <form action="{{route('subjects.update', $subject->id)}}" method="POST">
                            @csrf
                            @method('PATCH')
                            <input type="text" name="subject_name">
                            <button type="submit">Update</button>
                        </form>
                    </td>
                    <td>
                        <form action="{{route('subjects.destroy',$subject->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    @include('groups.students.edit.create_subject')
@endsection

resources/views/groups/students/edit/table_marks_store.blade.php
<div>
    <table class="table table-striped">
        <tbody>
            @foreach($subjects as $subject)
                <td>
                    <div>
                        <h2>{{$subject->subject_name}}</h2>
                        <form action="{{route('marks.store')}}" method="POST">
                            <input type="hidden" name="student" value="{{ $student->id  }}">
                            <input type="hidden" name="subject" value="{{ $subject->id  }}">
                            {{ csrf_field() }}
                            <div class="form-group">
                            <select name="mark">
                                <option value="" selected="selected"></option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Add</button>
                        </form>
                    </div>
                </td>
            @endforeach
        </tbody>
    </table>
</div>