routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('groups', 'GroupController');
Route::resource('students', 'StudentController');
Route::resource('marks', 'MarkController');
Route::resource('subjects', 'SubjectController');
Route::resource('photos', "PhotoController");


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = ['group_name', 'description'];

    public $timestamps = false;

    public function students()
    {
        return $this->hasMany(Student::class);
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use App\Models\Subject;

use App\Http\Requests\StoreGroup;
use Illuminate\Http\Request;

class GroupController extends Controller
{

    public function index()
    {
        $subjects = Subject::all();
        $groups = Group::all();

        return view('groups.show.index', compact('groups', 'subjects'));
    }

    public function create()
    {
        return view('groups.create');
    }

    public function store(StoreGroup $request)
    {
        Group::create($request->all());

        return redirect('groups');
    }

    public function edit(Group $group)
    {
        return view('groups.edit', compact('group'));
    }

    public function update(StoreGroup $request, Group $group)
    {
        $group->update($request->all());

        return redirect('groups')->with('success', 'Group has been updated');
    }

    public function show(Group $group)
    {
        $subjects = Subject::all();

        return view('groups.show', compact('group', 'subjects'));
    }

    public function destroy(Group $group)
    {
          $group->delete();

          return redirect('groups')->with('success', 'Group has been deleted');
    }
}

resources/views/groups/create.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div>
    <div>Add Group
    </div>
    <div class="card-body">
        <form method="post" action="{{ route('groups.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Group Name</label>
                <input type="text" class="form-control" name="group_name" />
            </div>
            <div class="form-group">
                <label for="birthday">Group Description</label>
                <input type="text" class="form-control" name="description" />
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
</div>

resources/views/groups/edit.blade.php
@extends('layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div>
        <div class="card-header">Add Group</div>

        <div class="card-body">
            <form method="POST" action="{{ route('groups.update', $group->id) }}">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="name">Group Name</label>
                    <input type="text" class="form-control" name="group_name" value={{$group->group_name}} />
                </div>
                <div class="form-group">
                    <label for="birthday">Group Description</label>
                    <input type="text" class="form-control" name="description" value={{$group->description}} />
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/groups/show.blade.php
@extends ('layouts.app')

@section ('content')
    <div>
        <table class="table table-striped">

            <thead>
              <tr>
                  <td>Student ID</td>
                  <td>Student Name</td>
                  <td>Student Birthday</td>
                  <td>Student Group</td>
                  @foreach($subjects as $subject)
                      <td>{{ $subject->subject_name }}</td>
                  @endforeach
                  @foreach($subjects as $subject)
                      <td>{{ $subject->subject_name }} Average</td>
                  @endforeach
                  <td>Average</td>
              </tr>
            </thead>

            <tbody>
            @php
            $collect = collect();
            @endphp
            @foreach($students as $student)
                @php
                    $collect->push($student->marks->avg('mark'));
                @endphp
                <tr>
                    <td>{{ $student->id }}</td>
                    <td>{{ $student->name }</td>
                    <td>{{ $student->birthday }}</td>
                    <td>{{ $student->group_id }}</td>

                    @foreach($subjects as $subject)
                        <td>
                            @foreach($student->marks as $mark)
                                @if($subject->id == $mark->subject_id)
                                    {{$mark->mark}}
                                @endif
                            @endforeach
                        </td>
                    @endforeach
                    @foreach($subjects as $subject)
                        <td>{{round($mark->where('student_id', $student->id)->where('subject_id', $subject->id)->avg('mark'),2)}}</td>
                    @endforeach
                        @php
                            $var = $student->marks->avg('mark');
                        @endphp
                    <td bgcolor="
                        @if ($var == 5)
                            lightgreen
                        @elseif ($var >= 4.5)
                            yellow
                        @elseif ($var <= 3)
                            red
                        @else
                            white
                        @endif
                    ">{{round($var ,2)}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <span>Group Average = {{ round($collect->avg(), 2) }}</span>
    </div>
@endsection